/**
 * Each object's partial series and mode shapes — **development only, and never
 * the source of anything the panel shows when a plug-in is connected.**
 *
 * This whole directory is a quarantine. All of the mathematics in this plug-in
 * belongs to the Rust engine: it computes the partials, the levels and the
 * ring times, and publishes them on the `modes`, `response` and `info`
 * streams. The panel draws what arrives and derives none of it.
 *
 * What this file is for is the hour before that engine exists, and the hour
 * after somebody clones the repository and wants to look at the page. The
 * design manifest in `../manifest.js` uses it to generate the same four
 * streams the engine will, so the panel has something to render — and the
 * panel cannot tell the difference, because it only ever sees a stream.
 *
 * **Nothing outside `src/dev/` may import this**, and nothing does. It is
 * loaded from a dynamic import behind `import.meta.env.DEV`, so a production
 * build does not contain a byte of it.
 *
 * ## The series are the engine's now, and this file no longer solves for them
 *
 * Every ratio here comes from `series-table.js`, which is generated by
 * `tools/gen-previews.mjs` out of `benchmark --dump series`. There used to be
 * a Newton solver for the beam's eigenvalues and a Bessel solver for the round
 * head's, and they were careful and tested and *still the wrong thing to
 * have*: two implementations of every eigenvalue problem in the product, with
 * nothing checking that they agreed. They had already drifted, silently, when
 * the engine appended two objects this page had never heard of.
 *
 * So the line is drawn at **root-finding and special functions, which are the
 * engine's**, against **closed-form algebra over a live control, which stays
 * here** — because a control that does nothing in design mode teaches the
 * wrong thing about the product. What remains is the rectangle's eigenvalues
 * (four lines, and `test/` checks them against the engine's own table), the
 * air column's phase, the stiff-string stretch, and the mode shapes.
 *
 * **One object's shape is not modelled**: the clamped disc's needs a modified
 * Bessel function, which is exactly the kind of machinery that just left. Its
 * contact controls do nothing in design mode and [`SHAPELESS`] says so, so the
 * panel can print it rather than let a dead knob look like a working one.
 *
 * **Two results are worth keeping even so**, both of which came out of writing
 * the tests: the beam ratio everyone quotes, 2.756, is a truncation of 2.75654
 * and not a rounding of it — the correctly rounded figure is 2.757 — and an
 * undercut bar has no closed form at all, so its ratios are a maker's target
 * rather than a solution.
 */
import { SERIES_TABLE, TABLE_LIMIT } from '../series-table.js';

/** Speed of sound in air at 20 °C, m/s. Only the air columns use it, and the panel prints it beside every length it derives. */
export const C_AIR = 343;

export { TABLE_LIMIT };

/**
 * The bare series of an object, `[i, j, ratio]` sorted by frequency, straight
 * off the engine.
 *
 * Bare means at default aspect with no inharmonicity: the controls that move a
 * series are applied on top of this, not baked into it.
 */
export const tableOf = (id) => SERIES_TABLE[id] || SERIES_TABLE.string;

/**
 * The objects whose mode shape this file does not model, so the design-mode
 * contact controls do nothing on them.
 *
 * The clamped disc's shape is `J_m(λu) − (J_m(λ)/I_m(λ))·I_m(λu)`, and the
 * modified Bessel function in the middle of it is the machinery this file
 * exists to no longer contain. The engine has it; design mode does without,
 * and the panel says which.
 */
export const SHAPELESS = new Set(['plate_round']);

// ---------------------------------------------------------------------------
// The three published constants the shapes need
// ---------------------------------------------------------------------------

/**
 * `β₁L` for a free–free bar: the first root of `cos x · cosh x = 1`.
 *
 * Not solved here any more. A beam's frequencies go as `(βₙ/β₁)²`, so the
 * engine's own ratio table gives every higher eigenvalue as `β₁√rₙ` — one
 * published number and a square root, rather than forty Newton iterations
 * that might not agree with the engine's forty.
 *
 * Leissa, NASA SP-160, Table 4.23.
 */
const BEAM_BETA1 = 4.730040744862704;

/**
 * `β₁L` for a bar clamped at one end: the first root of `cos x · cosh x = −1`.
 *
 * Leissa, NASA SP-160, Table 4.39. Same trick as the beam's, and the same
 * reason: the ratios come off the engine and this turns them back into the
 * eigenvalues the shape function wants.
 */
const TINE_BETA1 = 1.8751040687119413;

/**
 * `j₀₁`, the first zero of `J₀`, which is a round head's fundamental.
 *
 * A circular membrane's ratios are `j_{mn}/j₀₁`, so the engine's table times
 * this is the zero itself — and the shape function needs the zero, not the
 * ratio. Abramowitz & Stegun, Table 9.5.
 */
const BESSEL_J01 = 2.404825557695773;

// ---------------------------------------------------------------------------
// Bar mode shapes
// ---------------------------------------------------------------------------

/**
 * The mode shape of a free–free beam, `X(u)` for `u` along the bar.
 *
 * `X(u) = cosh(xu) + cos(xu) − σ(sinh(xu) + sin(xu))`, with
 * `σ = (cosh x − cos x)/(sinh x − sin x)`.
 *
 * The growing and decaying exponentials are separated before they are added,
 * because `σ → 1` as `x` grows and `cosh(xu) − σ·sinh(xu)` is then the
 * difference of two enormous and nearly equal numbers. Writing it as
 * `((1−σ)e^{xu} + (1+σ)e^{−xu})/2` and computing `1−σ` from its own closed
 * form keeps every digit.
 *
 * This is what makes a marimba bar's suspension cord go where it does: the
 * first mode's nodes are at 0.224 and 0.776 of the length, so a bar hung there
 * is held at the two points its fundamental does not move.
 *
 * @param {number} x The eigenvalue `βL` for this mode.
 * @param {number} u Position along the bar, 0 to 1.
 * @returns {number} The shape, ±2 at the free ends.
 */
export function beamShape(x, u) {
  const sinh = Math.sinh(x);
  const sin = Math.sin(x);
  const cos = Math.cos(x);
  // 1 − σ, from (sinh x − cosh x) = −e^−x. Never the subtraction of two
  // large numbers, however big x gets.
  const oneMinusSigma = (cos - sin - Math.exp(-x)) / (sinh - sin);
  const sigma = 1 - oneMinusSigma;
  const a = x * u;
  const growing = oneMinusSigma * Math.exp(a);
  const decaying = (1 + sigma) * Math.exp(-a);
  return (growing + decaying) / 2 + Math.cos(a) - sigma * Math.sin(a);
}

/**
 * The mode shape of a bar clamped at `u = 0` and free at `u = 1`.
 *
 * `X(u) = cosh(xu) − cos(xu) − σ(sinh(xu) − sin(xu))`, with
 * `σ = (cosh x + cos x)/(sinh x + sin x)`, rearranged the same way as the
 * free–free bar's and for the same reason.
 *
 * **Both clamped conditions fall out rather than being imposed**: `X(0) = 0`
 * and `X′(0) = 0` exactly, which is what "clamped" means, and getting them for
 * free is the check that the rearrangement did not change the function.
 */
export function tineShape(x, u) {
  const sinh = Math.sinh(x);
  const sin = Math.sin(x);
  const cos = Math.cos(x);
  // 1 − σ = (sinh x + sin x − cosh x − cos x)/(sinh x + sin x), and
  // sinh x − cosh x = −e^−x, so the numerator never subtracts two large
  // numbers either.
  const oneMinusSigma = (sin - cos - Math.exp(-x)) / (sinh + sin);
  const sigma = 1 - oneMinusSigma;
  const a = x * u;
  const growing = oneMinusSigma * Math.exp(a);
  const decaying = (1 + sigma) * Math.exp(-a);
  return (growing + decaying) / 2 - Math.cos(a) + sigma * Math.sin(a);
}

// ---------------------------------------------------------------------------
// Rectangular membrane and plate
// ---------------------------------------------------------------------------

/** How far the `(a, b)` mode indices run when the eigenvalues are enumerated. Well past any partial count the panel offers. */
const RECT_ORDER = 24;

/**
 * The mode indices and eigenvalues of a rectangle of aspect `r`, sorted and
 * normalised so the first is 1.
 *
 * `f(a,b) ∝ √(a² + b²/r²)` for a tensioned membrane. Two indices run
 * independently, so the series is dense and has no common divisor — which is
 * exactly why a drum is not pitched the way a string is, and why raising the
 * partial count on a membrane fills the axis in rather than extending it.
 *
 * **This is the one series still solved on the page, because Ratio is a
 * control and the engine's table is one aspect.** Four lines of algebra, no
 * root finding — and `test/` asserts that at aspect 1 it reproduces the
 * engine's own membrane and plate tables exactly, so the two cannot drift.
 *
 * @param {number} n How many partials.
 * @param {number} r Aspect ratio of the rectangle.
 * @returns {{ ratio: number, a: number, b: number }[]}
 */
export function rectModes(n, r = 1) {
  const all = [];
  for (let a = 1; a <= RECT_ORDER; a++) {
    for (let b = 1; b <= RECT_ORDER; b++) all.push({ a, b, ratio: Math.sqrt(a * a + (b * b) / (r * r)) });
  }
  all.sort((x, y) => x.ratio - y.ratio);
  const f0 = all[0].ratio;
  return all.slice(0, n).map((m) => ({ ...m, ratio: m.ratio / f0 }));
}

// ---------------------------------------------------------------------------
// Circular membrane
// ---------------------------------------------------------------------------

/**
 * The Bessel function of the first kind, from its integral form:
 * `J_m(x) = (1/π) ∫₀^π cos(mθ − x sin θ) dθ`.
 *
 * Kept for the round head's **shape** only; its zeros — the ratios — come off
 * the engine now. The power series is the usual way and it is the wrong way
 * here: by the time `x` is past twenty its terms alternate through numbers far
 * larger than the answer and the result is noise. The integrand is bounded by
 * one for every `x`, so Simpson's rule on it cannot lose what it never had.
 */
export function besselJ(m, x) {
  const N = 512;
  const h = Math.PI / N;
  // The two endpoints, sin θ being zero at both, then Simpson's alternating weights.
  let sum = 1 + Math.cos(m * Math.PI);
  for (let i = 1; i < N; i++) {
    const th = i * h;
    sum += (i % 2 ? 4 : 2) * Math.cos(m * th - x * Math.sin(th));
  }
  return (sum * h) / 3 / Math.PI;
}

// ---------------------------------------------------------------------------
// The air column
// ---------------------------------------------------------------------------

/**
 * The round-trip phase offset of the loop, in radians, for an `opening` of 0
 * to 1.
 *
 * A stopped pipe reflects `+1` at the closed end and `−1` at the open one, so
 * the round trip inverts: half a turn of phase, and only the odd harmonics
 * survive. A tube open at both ends reflects `−1` twice, the round trip is
 * back where it started, and the whole series is there. **That single sign is
 * the entire difference between the two objects**, and because it is a phase
 * rather than a switch it has a continuum between its ends.
 */
export const openingPhase = (opening) => Math.PI * (1 - opening);

/**
 * Partial ratios of an air column at a given opening.
 *
 * Resonance is where the round trip comes back in phase: `2πfT + ψ = 2πk`.
 * Pinning the first resonance to the fundamental fixes the loop delay at
 * `T = (1 − ψ/2π)/f₀`, and every other partial follows.
 *
 * Stopped (`ψ = π`) gives 1, 3, 5, 7 …; open (`ψ = 0`) gives 1, 2, 3, 4 …;
 * and the sweep between them slides the upper partials continuously, which is
 * what makes Opening a real control rather than a second type switch.
 *
 * **Kept as a closed form here because Opening is a control.** The engine's
 * dump measures its air columns off the running delay loop, which is what the
 * browse rows draw — but at one setting of Opening each, and this has to sweep
 * between them. `test/` holds the two against each other: they agree to a
 * fraction of a cent at the bottom of the series and drift sharp above it,
 * because a real loop with a filtered reflection is dispersive and an ideal
 * one is not. That drift is the engine's to have; the panel draws the engine's
 * own partials whenever one is connected.
 *
 * @param {number} n How many partials.
 * @param {number} opening 0 stopped, 1 open at both ends.
 */
export function guideRatios(n, opening = 1) {
  const psi = openingPhase(opening) / (2 * Math.PI);
  return Array.from({ length: n }, (_, i) => (i + 1 - psi) / (1 - psi));
}

/**
 * How long the air column actually is, in metres, for a fundamental and an
 * opening — the tube the engine is standing in for.
 *
 * The column is `Λ` wavelengths long, `Λ = (1 − ψ/2π)/2`: half a wavelength
 * open at both ends, a quarter stopped. So **a stopped pipe is half the
 * length of an open one at the same pitch**, which is the same fact as "the
 * same pipe stopped sounds an octave lower", read the other way round.
 *
 * @param {number} f0 Fundamental, Hz.
 * @param {number} opening 0 to 1.
 * @param {number} radiusMm Bore radius, for the end correction.
 */
export function columnLength(f0, opening, radiusMm = 0) {
  const lambdas = (1 - openingPhase(opening) / (2 * Math.PI)) / 2;
  // An open end behaves as though the column ran on a little past it; the
  // classic unflanged figure is 0.6 of the bore radius, and there is one such
  // end for every end that is open.
  const correction = 0.6 * (radiusMm / 1000) * (1 + opening);
  return Math.max(0, (C_AIR * lambdas) / Math.max(1e-6, f0) - correction);
}

/** The loop delay, in seconds, that puts an air column's first resonance on `f0`. */
export const loopDelay = (f0, opening) => (1 - openingPhase(opening) / (2 * Math.PI)) / Math.max(1e-6, f0);

// ---------------------------------------------------------------------------
// The objects
// ---------------------------------------------------------------------------

/**
 * The marimba's tuned partials, as the two choices a maker actually makes.
 *
 * A marimba bar is deliberately **not** a uniform bar: the maker cuts an arch
 * out of the underside, which lowers the second partial far more than the
 * first and lands it on a low whole ratio. That retuning is the whole reason
 * it reads as pitched where a glockenspiel clangs, and the whole reason this
 * is a separate model rather than the beam with a filter on it.
 *
 * **Neither number is a constant, and the panel does not pretend otherwise.**
 * The second partial is cut to 4 — two octaves — for a marimba and to 3 — a
 * twelfth — for a xylophone, and both instruments exist. The third is given
 * as about 9.2 in one source and 10 in another, and that is not a discrepancy
 * to average away: it depends on how deeply the bar is undercut, so it is a
 * builder's choice and both values are right for the bar their author was
 * holding. Averaging two sources into 9.6 would produce a bar nobody has ever
 * made. So both are on the panel, as controls.
 */
export const BAR_SECOND = [4, 3];
export const BAR_THIRD = [9.2, 10];

/**
 * A tuned bar's series: the two chosen partials, and then the beam again.
 *
 * Above the third the undercut stops controlling anything and the bar goes
 * back to behaving like a uniform beam, so that is what the series does —
 * scaled to continue from wherever the tuned third was put. The beam it
 * continues into is the engine's, off the table.
 */
export function barRatios(n, second = BAR_SECOND[0], third = BAR_THIRD[0]) {
  const beam = tableOf('beam').map((m) => m[2]);
  const tuned = [1, second, third].slice(0, n);
  if (n <= 3) return tuned;
  const scale = third / beam[2];
  return tuned.concat(beam.slice(3, n).map((r) => r * scale));
}

/**
 * The series and mode shape for each object, keyed by the id the catalogue in
 * `src/objects.js` uses. Physics only: what a thing is called, what it is for
 * and where its numbers are cited from all live in the catalogue, because
 * those are things the panel prints and these are things the engine computes.
 *
 * `ratios` returns **as many partials as the object has**, up to the `n`
 * asked for — never a padded list. A bar has twenty-nine below four hundred
 * times its fundamental and a tine has twelve, and that is a fact about the
 * object rather than a limit to hide.
 *
 * @type {Record<string, { ratios: (n: number, o: object) => number[], shape: (k: number, u: number, o: object) => number }>}
 */
const fromTable = (id) => (n) => tableOf(id).slice(0, n).map((m) => m[2]);

export const SERIES = {
  beam: {
    ratios: fromTable('beam'),
    shape: (k, u) => barShapeNorm('beam', k, u),
  },
  marimba: {
    ratios: (n, o = {}) => barRatios(n, o.barSecond ?? BAR_SECOND[0], o.barThird ?? BAR_THIRD[0]),
    // The uniform bar's, which the catalogue marks as an approximation: the
    // arch that retunes the partials moves the nodes too.
    shape: (k, u) => barShapeNorm('beam', k, u),
  },
  string: {
    ratios: fromTable('string'),
    shape: (k, u) => Math.sin((k + 1) * Math.PI * u),
  },
  membrane: {
    ratios: (n, o = {}) => rectModes(n, o.ratio ?? 1).map((m) => m.ratio),
    shape: (k, u, o = {}) => rectShape(k, u, o.ratio ?? 1),
  },
  plate: {
    ratios: (n, o = {}) => rectModes(n, o.ratio ?? 1).map((m) => m.ratio ** 2),
    shape: (k, u, o = {}) => rectShape(k, u, o.ratio ?? 1),
  },
  pipe: {
    ratios: (n, o = {}) => guideRatios(n, o.opening ?? 0),
    shape: (k, u, o = {}) => guideShape(k, u, o.opening ?? 0),
  },
  tube: {
    ratios: (n, o = {}) => guideRatios(n, o.opening ?? 1),
    shape: (k, u, o = {}) => guideShape(k, u, o.opening ?? 1),
  },
  membrane_round: {
    ratios: fromTable('membrane_round'),
    shape: (k, u) => circleShape(k, u),
  },
  tine: {
    ratios: fromTable('tine'),
    shape: (k, u) => barShapeNorm('tine', k, u),
  },
  plate_round: {
    ratios: fromTable('plate_round'),
    // Not modelled here; see SHAPELESS. Uniform weight, so a strike takes the
    // same from every mode and the panel says the control is inert.
    shape: () => 1,
  },
};

/**
 * How hard mode `k` is driven by a strike (or heard by a pickup) at `u`.
 *
 * **Striking at a node gives that mode no energy at all.** It is the same
 * reason plucking a string at a fifth of its length kills the fifth harmonic,
 * and the same reason a marimba bar hangs from a cord threaded through it at
 * 0.224 of its length: those are the two places the fundamental does not
 * move, so the cord takes nothing from it.
 */
export function nodeWeight(id, k, u, opts = {}) {
  const e = SERIES[id] || SERIES.string;
  return Math.abs(e.shape(k, Math.min(1, Math.max(0, u)), opts));
}

/** The partial ratios of an object, by id. */
export const ratiosOf = (id, n, opts = {}) => (SERIES[id] || SERIES.string).ratios(n, opts);

/**
 * A mode's own indices, `(i, j)`, for the objects that have two.
 *
 * A one-dimensional object has one index and the partial number *is* it. A
 * surface has two that run independently — which is the whole reason its
 * series is dense — and a disc's are the number of nodal diameters and the
 * number of nodal circles. Naming them is the difference between "partial 14"
 * and "the mode with three nodal diameters and two nodal circles", and the
 * second is the one that tells you why it sounds like that.
 *
 * `j` is 0 where there is no second index, which is how the panel reads
 * "this object has only one". These come off the engine's table with the
 * ratios, so an override addresses the mode the audio thread calls by that
 * name rather than one the page numbered itself.
 */
export function modeIndices(id, n, opts = {}) {
  if (id === 'membrane' || id === 'plate') {
    return rectModes(n, opts.ratio ?? 1).map((m) => [m.a, m.b]);
  }
  if (id === 'pipe' || id === 'tube') {
    return Array.from({ length: n }, (_, k) => [k + 1, 0]);
  }
  return tableOf(id)
    .slice(0, n)
    .map((m) => [m[0], m[1]]);
}

// ---------------------------------------------------------------------------
// Mode shapes, normalised
// ---------------------------------------------------------------------------

/**
 * Bar mode shapes, normalised so an antinode reads 1.
 *
 * The eigenvalue comes from the engine's ratio: a bar's frequencies go as
 * `(βₙ/β₁)²`, so `βₙ = β₁√rₙ` exactly, for either end condition. The peak is
 * found on a grid once per mode and cached, because the panel asks for these
 * on every frame.
 */
const barPeak = new Map();
function barShapeNorm(family, k, u) {
  const key = `${family}:${k}`;
  let e = barPeak.get(key);
  if (e === undefined) {
    const rows = tableOf(family);
    const r = rows[Math.min(k, rows.length - 1)][2];
    const beta1 = family === 'tine' ? TINE_BETA1 : BEAM_BETA1;
    const x = beta1 * Math.sqrt(Math.max(1, r));
    const f = family === 'tine' ? tineShape : beamShape;
    let peak = 0;
    for (let i = 0; i <= 256; i++) peak = Math.max(peak, Math.abs(f(x, i / 256)));
    e = { x, peak: peak || 1, f };
    barPeak.set(key, e);
  }
  return e.f(e.x, u) / e.peak;
}

/**
 * A rectangle's mode shape, read along the diagonal.
 *
 * `X(u,v) = sin(aπu)·sin(bπv)` over the two dimensions, and Hit and Pos are
 * one number each, so the panel walks the diagonal: `u = v`. **That is a
 * choice the panel is making, not something the physics forced** — a real
 * strike lands somewhere in a square and has two coordinates. The diagonal is
 * the path that meets every mode's nodes in both indices, so it is the one
 * that shows the effect the control exists for.
 */
const rectCache = new Map();
function rectShape(k, u, r) {
  const key = `${r}`;
  let list = rectCache.get(key);
  if (!list) {
    list = rectModes(RECT_ORDER * RECT_ORDER, r);
    rectCache.set(key, list);
  }
  const m = list[Math.min(k, list.length - 1)];
  return Math.sin(m.a * Math.PI * u) * Math.sin(m.b * Math.PI * u);
}

/**
 * A circular head's mode shape along a radius: `J_m(j_{mn}·u)`, with `u`
 * running from the centre to the rim.
 *
 * Its nodes are **circles**, not points, which is a genuinely different thing
 * to strike than a bar or a string: every mode is zero at the rim, so hitting
 * a drum on its edge takes almost nothing from anything, and the nodal
 * circles of the higher modes march inward. The panel walks the radius,
 * because Hit and Pos are one number each.
 *
 * The zero is `j₀₁` times the engine's ratio, which is what that ratio means.
 */
const circlePeak = new Map();
function circleShape(k, u) {
  const rows = tableOf('membrane_round');
  const row = rows[Math.min(k, rows.length - 1)];
  const m = row[0];
  const zero = BESSEL_J01 * row[2];
  let peak = circlePeak.get(k);
  if (peak === undefined) {
    peak = 0;
    for (let i = 0; i <= 128; i++) peak = Math.max(peak, Math.abs(besselJ(m, zero * (i / 128))));
    circlePeak.set(k, peak || 1);
  }
  return besselJ(m, zero * u) / peak;
}

/**
 * The standing wave of an air column at partial `k`, at a fraction `u` of the
 * way from the far end to the mouth.
 *
 * The column is `Λ = (1 − ψ/2π)/2` wavelengths of the fundamental long, so
 * partial `k` turns `2π·(fₖ/f₀)·Λ` radians of phase across it. Stopped, that
 * puts a node hard against the closed end; open, an antinode at both. One
 * expression covers the whole sweep, which is the point: **the excitation
 * point works on a waveguide for the same reason it works on a string**, and
 * the panel does not need a second story for it.
 */
function guideShape(k, u, opening) {
  const psi = openingPhase(opening) / (2 * Math.PI);
  const lambdas = (1 - psi) / 2;
  const rk = (k + 1 - psi) / (1 - psi);
  return Math.sin(2 * Math.PI * rk * lambdas * u);
}

// ---------------------------------------------------------------------------
// Inharmonicity
// ---------------------------------------------------------------------------

/**
 * The largest stiff-string coefficient the Inharm control reaches, copied from
 * `dsp::engine::INHARM_B_MAX`. Ten times the value Lehtonen and colleagues
 * measured for a piano C4, so the physical region sits in the first third of
 * the travel and the rest is the synthetic extension.
 */
export const INHARM_B_MAX = 3.0e-3;

/**
 * The coefficient the control is asking for, from `Settings::inharm_b`.
 *
 * Quadratic in the control so that the region a real string lives in — `B`
 * around `3 × 10⁻⁴` for a piano C4 — sits where a knob can be placed on it
 * rather than in the first pixel.
 *
 * @param {number} inharm The control, −1 to 1.
 */
export const inharmB = (inharm) => {
  const x = Math.max(-1, Math.min(1, inharm));
  return INHARM_B_MAX * x * x * Math.sign(x);
};

/**
 * Inharm, applied to a series — **the engine's law, copied from
 * `Object::ratio`**, not a stand-in for it.
 *
 * `r → r·√(1 + |B|r²)` for a positive coefficient and `r → r/√(1 + |B|r²)` for
 * a negative one. The first is the stiff-string law, `fₙ = n·f₁·√(1 + Bn²)`,
 * which is one object's physics applied to every object here; the second is
 * the same expression run backwards, compressing the partials the way nothing
 * physical does, and the docs call that the synthetic half of the control.
 *
 * This file used to apply a log-axis stretch instead and say plainly that it
 * was not the stiff-string law. It was honest and it was still wrong, because
 * the engine's law *is* the stiff-string law and a stand-in that disagrees
 * with the thing it stands in for teaches the wrong shape.
 */
export const stretch = (ratios, inharm) => {
  const b = inharmB(inharm);
  if (b === 0) return ratios;
  const mag = Math.abs(b);
  return ratios.map((r) => {
    if (r === 0) return r;
    const s = Math.sqrt(1 + mag * r * r);
    return b > 0 ? r * s : r / s;
  });
};
