/**
 * Characteristic partial ratios, one row per object, for the browse view's
 * previews — **a generated table, not a computation.**
 *
 * The panel renders and does not compute: every partial it draws for the
 * loaded object arrives on the `modes` stream. A browser showing eight
 * objects at once cannot do that, because only one of them is loaded, and
 * solving eight beam equations in the front end to draw eight thumbnails is
 * exactly what this architecture forbids. So the rows read a table.
 *
 * **These are the shape of each series, not your settings.** They are taken
 * at reference settings, so a row shows what an object *is* rather than what
 * it would sound like at your current damping — which is the comparison the
 * browser exists to make anyway.
 *
 * Generated by `tools/gen-previews.mjs` from the design-mode physics. The
 * engine is the authority: when its ratios move, regenerate this.
 *
 * @type {Record<string, number[]>}
 */
export const PREVIEW_RATIOS = {
  beam: [1, 2.75654, 5.40392, 8.93295, 13.3443, 18.6379, 24.8138, 31.8719, 39.8123, 48.635, 58.3399, 68.9271, 80.3966, 92.7483, 105.982, 120.099, 135.097, 150.978, 167.741, 185.386, 203.914, 223.324, 243.616, 264.79, 286.847, 309.786, 333.607, 358.311, 383.896, 410.364, 437.715, 465.947, 495.062, 525.059, 555.938, 587.7, 620.344, 653.87, 688.278, 723.569],
  marimba: [1, 4, 9.2, 15.2081, 22.7182, 31.7304, 42.2446, 54.2609, 67.7792, 82.7995, 99.3218, 117.346, 136.873, 157.901, 180.432, 204.464, 229.999, 257.035, 285.574, 315.614, 347.157, 380.202, 414.748, 450.797, 488.348, 527.401, 567.956, 610.013, 653.572, 698.632, 745.195, 793.26, 842.828, 893.897, 946.468, 1000.54, 1056.12, 1113.19, 1171.77, 1231.85],
  string: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
  membrane: [1, 1.58114, 1.58114, 2, 2.23607, 2.23607, 2.54951, 2.54951, 2.91548, 2.91548, 3, 3.16228, 3.16228, 3.53553, 3.53553, 3.60555, 3.60555, 3.80789, 3.80789, 4, 4.12311, 4.12311, 4.30116, 4.30116, 4.47214, 4.47214, 4.52769, 4.52769, 4.74342, 4.74342, 5, 5, 5, 5.09902, 5.09902, 5.14782, 5.14782, 5.38516, 5.38516, 5.52268],
  plate: [1, 2.5, 2.5, 4, 5, 5, 6.5, 6.5, 8.5, 8.5, 9, 10, 10, 12.5, 12.5, 13, 13, 14.5, 14.5, 16, 17, 17, 18.5, 18.5, 20, 20, 20.5, 20.5, 22.5, 22.5, 25, 25, 25, 26, 26, 26.5, 26.5, 29, 29, 30.5],
  pipe: [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79],
  tube: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
  membrane_round: [1, 1.59334, 2.13555, 2.29542, 2.65307, 2.9173, 3.15546, 3.50015, 3.59848, 3.64745, 4.05893, 4.13174, 4.23044, 4.60104, 4.61005, 4.83189, 4.90328, 5.08357, 5.13077, 5.41212, 5.5404, 5.55313, 5.65084, 5.97654, 6.01936, 6.15261, 6.16314, 6.20873, 6.48274, 6.52861, 6.669, 6.74621, 6.84899, 6.94364, 7.07071, 7.16943, 7.32526, 7.40238, 7.46824, 7.5145],
};
